---
type: 'gold'
images:
  'ubuntu_2004':
    'name':             'GOLD Ubuntu 20.04 LTS'
    'depricated':       'Outdated (Ubuntu 20.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2004-latest.qcow2'
    'builder_checksum': 'ubuntu_2004-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'ubuntu_2204':
    'name':             'GOLD Ubuntu 22.04 LTS'
    'depricated':       'Outdated (Ubuntu 22.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2204-latest.qcow2'
    'builder_checksum': 'ubuntu_2204-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'centos7':
    'name':             'GOLD CentOS 7'
    'depricated':       'Outdated (CentOS 7)'
    'url':              'http://builder/'
    'latest':           'centos7-latest.qcow2'
    'builder_checksum': 'centos7-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'centosstream8':
    'name':             'GOLD CentOS Stream 8'
    'depricated':       'Outdated (CentOS Stream 8)'
    'url':              'http://builder/'
    'latest':           'centosstream8-latest.qcow2'
    'builder_checksum': 'centosstream8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'centosstream9':
    'name':             'GOLD CentOS Stream 9'
    'depricated':       'Outdated (CentOS Stream 9)'
    'url':              'http://builder/'
    'latest':           'centosstream9-latest.qcow2'
    'builder_checksum': 'centosstream9-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'almalinux8':
    'name':             'GOLD Alma Linux 8'
    'depricated':       'Outdated (Alma Linux 8)'
    'url':              'http://builder/'
    'latest':           'almalinux8-latest.qcow2'
    'builder_checksum': 'almalinux8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'almalinux9':
    'name':             'GOLD Alma Linux 9'
    'depricated':       'Outdated (Alma Linux 9)'
    'url':              'http://builder/'
    'latest':           'almalinux9-latest.qcow2'
    'builder_checksum': 'almalinux9-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'rockylinux8':
    'name':             'GOLD Rocky Linux 8'
    'depricated':       'Outdated (Rocky Linux 8)'
    'url':              'http://builder/'
    'latest':           'rockylinux8-latest.qcow2'
    'builder_checksum': 'rockylinux8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'rockylinux9':
    'name':             'GOLD Rocky Linux 9'
    'depricated':       'Outdated (Rocky Linux 9)'
    'url':              'http://builder/'
    'latest':           'rockylinux9-latest.qcow2'
    'builder_checksum': 'rockylinux9-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'debian10':
    'name':             'GOLD Debian 10'
    'depricated':       'Outdated (Debian 10)'
    'url':              'http://builder/'
    'latest':           'debian10-latest.qcow2'
    'builder_checksum': 'debian10-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'debian11':
    'name':             'GOLD Debian 11'
    'depricated':       'Outdated (Debian 11)'
    'url':              'http://builder/'
    'latest':           'debian11-latest.qcow2'
    'builder_checksum': 'debian11-latest.md5'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'debian12':
    'name':             'GOLD Debian 12'
    'depricated':       'Outdated (Debian 12)'
    'url':              'http://builder/'
    'latest':           'debian12-latest.qcow2'
    'builder_checksum': 'debian12-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_rng_model':              'virtio'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
  'fedora_38':
    'name':             'GOLD Fedora 38'
    'depricated':       'Outdated (Fedora 38)'
    'url':              'http://builder/'
    'latest':           'fedora_38-latest.qcow2'
    'builder_checksum': 'fedora_38-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_rng_model':              'virtio'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
