---
type: 'gold'
images:
  'ubuntu_1804':
    'name':             'GOLD Ubuntu 18.04 LTS'
    'depricated':       'Outdated (Ubuntu 18.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_1804-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'ubuntu_2004':
    'name':             'GOLD Ubuntu 20.04 LTS'
    'depricated':       'Outdated (Ubuntu 20.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2004-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'ubuntu_2104':
    'name':             'GOLD Ubuntu 21.04'
    'depricated':       'Outdated (Ubuntu 21.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2104-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'centos7':
    'name':             'GOLD CentOS 7'
    'depricated':       'Outdated (CentOS 7)'
    'url':              'http://builder/'
    'latest':           'centos7-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'centosstream8':
    'name':             'GOLD CentOS Stream 8'
    'depricated':       'Outdated (CentOS Stream 8)'
    'url':              'http://builder/'
    'latest':           'centosstream8-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
  'almalinux8':
    'name':             'GOLD Alma Linux 8'
    'depricated':       'Outdated (Alma Linux 8)'
    'url':              'http://builder/'
    'latest':           'almalinux8-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'hw_firmware_type':       'uefi'
      'os_require_quiesce':     'yes'
  'rockylinux8':
    'name':             'GOLD Rocky Linux 8'
    'depricated':       'Outdated (Rocky Linux 8)'
    'url':              'http://builder/'
    'latest':           'rockylinux8-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
  'debian9':
    'name':             'GOLD Debian 9'
    'depricated':       'Outdated (Debian 9)'
    'url':              'http://builder/'
    'latest':           'debian9-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'debian10':
    'name':             'GOLD Debian 10'
    'depricated':       'Outdated (Debian 10)'
    'url':              'http://builder/'
    'latest':           'debian10-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
  'debian11':
    'name':             'GOLD Debian 11'
    'depricated':       'Outdated (Debian 11)'
    'url':              'http://builder/'
    'latest':           'debian11-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'hw_firmware_type':       'uefi'
      'os_require_quiesce':     'yes'
  'fedora_34':
    'name':             'GOLD Fedora 34'
    'depricated':       'Outdated (Fedora 34)'
    'url':              'http://builder/'
    'latest':           'fedora_34-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'public'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_rng_model':           'virtio'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':  'yes'
