---
type: 'gold'
images:
  'centos6':
    'name':             'GOLD CentOS 6'
    'depricated':       'Outdated (CentOS 6)'
  'fedora_27':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
  'fedora_28':
    'name':             'GOLD Fedora 27'
    'depricated':       'Outdated (Fedora)'
  'fedora_29':
    'name':             'GOLD Fedora 29'
    'depricated':       'Outdated (Fedora)'
  'fedora_30':
    'name':             'GOLD Fedora 30'
    'depricated':       'Outdated (Fedora)'
  'fedora_31':
    'name':             'GOLD Fedora 31'
    'depricated':       'Outdated (Fedora 31)'
  'fedora_32':
    'name':             'GOLD Fedora 32'
    'depricated':       'Outdated (Fedora 32)'
  'fedora_33':
    'name':             'GOLD Fedora 33'
    'depricated':       'Outdated (Fedora 33)'
  'ubuntu_1604':
    'name':             'GOLD Ubuntu 16.04 LTS'
    'depricated':       'Outdated (Ubuntu 16.04)'
  'ubuntu_1904':
    'name':             'GOLD Ubuntu 19.04 LTS'
    'depricated':       'Outdated (Ubuntu 19.04)'
  'ubuntu_1910':
    'name':             'GOLD Ubuntu 19.10'
    'depricated':       'Outdated (Ubuntu 19.10)'
