---
type: 'uio'
images:
  'uio_rhel7':
    'name':             'UiO Managed RHEL 7'
    'depricated':       'Outdated (UiO RHEL7)'
    'url':              'http://builder/'
    'latest':           'uio_rhel7-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
  'uio_rhel8':
    'name':             'UiO Managed RHEL 8'
    'depricated':       'Outdated (UiO RHEL8)'
    'url':              'http://builder/'
    'latest':           'uio_rhel8-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
