---
type: 'vgpu'
images:
  'ubuntu_2004':
    'name':             'vGPU Ubuntu 20.04 LTS'
    'depricated':       'Outdated vGPU (Ubuntu 20.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2004_nv_vgpu-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
  'almalinux8':
    'name':             'vGPU Alma Linux 8'
    'depricated':       'Outdated vGPU (Alma Linux 8)'
    'url':              'http://builder/'
    'latest':           'almalinux8_nv_vgpu-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'hw_firmware_type':       'uefi'
      'os_require_quiesce':     'yes'
