---
type: 'vgpu'
images:
  'ubuntu_2004':
    'name':             'vGPU Ubuntu 20.04 LTS'
    'depricated':       'Outdated vGPU (Ubuntu 20.04)'
    'url':              'http://builder/'
    'latest':           'ubuntu_2004_nv_vgpu-latest.qcow2'
    'min_ram':          768
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
  'centos7':
    'name':             'vGPU CentOS 7'
    'depricated':       'Outdated vGPU (CentOS 7)'
    'url':              'http://builder/'
    'latest':           'centos7_nv_vgpu-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
  'centos8':
    'name':             'vGPU CentOS 8'
    'depricated':       'Outdated vGPU (CentOS 8)'
    'url':              'http://builder/'
    'latest':           'centos8_nv_vgpu-latest.qcow2'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
