---
# M1 flavor used for Alice
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 2048
  hw_rng:rate_period: 1
  hw:numa_nodes: 1
  hw:cpu_sockets: 1
  hw:cpu_policy: 'dedicated'
  hw:cpu_thread_policy: 'require'
  hw:mem_page_size: 2048
  aggregate_instance_extra_specs:type: 's== alice'

# Memmory calclulation
# 61440 = total memmory in hugepages in a numa node
# We always set ram 2 MB lower per flavor type to be safe
# Example: 2xlarge
# (61440 / 2) - 2 = 30718

alice.m1a:
  'alice.m1a.xlarge': # this is for testing
    vcpus: 4
    ram: 15358
    disk: 20
  'alice.m1a.2xlarge':
    vcpus: 8
    ram: 30718
    disk: 100 # vcpu*10 + 20
  'alice.m1a.4xlarge':
    vcpus: 16
    ram: 61438
    disk: 180 # vcpu*10 + 20
