---
# Flavor used for Clarino
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 2048
  hw_rng:rate_period: 1
  hw:numa_nodes: 4
  hw:cpu_sockets: 2
  hw:cpu_policy: 'dedicated'
  hw:cpu_thread_policy: 'require'
  hw:mem_page_size: 2048
  aggregate_instance_extra_specs:type: 's== clarino'

# Memmory calclulation
# 61440 = total memmory in hugepages in a numa node
# We always set ram 2 MB lower per flavor type to be safe
# Example: 2xlarge
# (61440 / 2) - 2 = 30718

clarino:
  'clarino.48xlarge': # one kembo flavor to fill a host
    vcpus: 96
    ram: 1007608
    disk: 5800
