---
# M1 flavor - default
public: true
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
m1: # (4x)
  'm1.tiny': # [1-0,5-1]
    vcpus: 1
    ram: 512
    disk: 2
  'm1.small': # [1-2-10]
    vcpus: 1
    ram: 2048
    disk: 10
  'm1.medium': # [1-4-20] (updated)
    vcpus: 1
    ram: 4096
    disk: 20
  'm1.large': # [2-8-20] (updated)
    vcpus: 2
    ram: 8192
    disk: 20
  'm1.xlarge': # [4-16-20] (new)
    vcpus: 4
    ram: 16384
    disk: 20
