---
# R1 flavor - more RAM than default
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
r1: # (8x) new
  'r1.medium': # [1-8-20]
    vcpus: 1
    ram: 8192
    disk: 20
  'r1.large': # [2-16-20]
    vcpus: 2
    ram: 16384
    disk: 20
  'r1.xlarge': # [4-32-20]
    vcpus: 4
    ram: 32768
    disk: 20
  'r1.2xlarge': # [8-64-20]
    vcpus: 8
    ram: 65536
    disk: 20
  'r1.4xlarge': # [16-128-20]
    vcpus: 16
    ram: 131072
    disk: 20
