---
# C1 flavor used for Robin
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 2048
  hw_rng:rate_period: 1
  hw:numa_nodes: 1
  hw:cpu_sockets: 1
  hw:cpu_policy: 'dedicated'
  hw:cpu_thread_policy: 'require'
  hw:mem_page_size: 2048
  aggregate_instance_extra_specs:type: 's== robin'

# Memmory calculations:
# Total: 491520 MB
# We always set ram (1920MB) 2MB lower per flavor type to be safe
# (ram pr vcpu)x(vcpu)-2x(numa_nodes)
# Example:
# 2xlarge  (491520 / 16) - 2 =  30718
# 8xlarge  (491520 / 4)  - 2 = 122878
# 32xlarge (491520 / 1)  - 2 = 491518

robin.c1a:
  'robin.c1a.2xlarge':
    vcpus: 8
    ram: 15358
    disk: 12
  'robin.c1a.4xlarge':
    vcpus: 16
    ram: 30718
    disk: 25
  'robin.c1a.8xlarge':
    vcpus: 32
    ram: 61438
    disk: 50
  'robin.c1a.16xlarge':
    vcpus: 64
    ram: 122878
    disk: 100
  'robin.c1a.32xlarge':
    vcpus: 128
    ram: 245758
    disk: 200
  'robin.c1a.64xlarge':
    vcpus: 240
    ram: 460796
    disk: 400
    properties:
      hw:numa_nodes: 2
      hw:cpu_sockets: 2
