---
# vgpu m1 flavor for all regions
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
  aggregate_instance_extra_specs:type: 's== vgpu'
  resources:VGPU: '1'
vgpu.m1:
  'vgpu.m1.large':
    vcpus: 2
    ram: 8192
    disk: 20
  'vgpu.m1.xlarge':
    vcpus: 4
    ram: 16384
    disk: 20
  'vgpu.m1.2xlarge':
    vcpus: 8
    ram: 32768
    disk: 20
