language: python

sudo: required

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsasl2-dev libldap2-dev libssl-dev python2.7-dev

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
#  - pylint -E himlarcli
  - find . -maxdepth 1 -type f  \( -iname "*.py" ! -iname "setup.py" \)  | xargs pylint -E
