---
direction:
  - egress
protocol:
  - ipv6-icmp
  - icmp
remote_group_id: ["!None"]
port:
  - 22
  - 80
  - 443
remote_ip_prefix:
  - 10.1.0.0/22          # BGO: private1_IPv4
  - 158.39.77.0/24       # BGO: public1_IPv4
  - 158.39.74.0/24       # BGO: public2_IPv4
  - 158.39.201.0/24      # BGO: public4_IPv4
  - 158.37.65.0/24       # BGO: public5_IPv4
  - 2001:700:2:8301::/64 # BGO: public1_IPv6
  - 2001:700:2:8300::/64 # BGO: public2_IPv6
  - 10.2.0.0/22          # OSL: private1_IPv4
  - 158.37.63.0/24       # OSL: public1_IPv4
  - 158.39.75.0/24       # OSL: public2_IPv4
  - 158.39.48.0/24       # OSL: public4_IPv4
  - 158.39.200.0/24      # OSL: public5_IPv4
  - 2001:700:2:8201::/64 # OSL: public1_IPv6
  - 2001:700:2:8200::/64 # OSL: public2_IPv6
  - 129.177.0.0/16       # UiB IPv4 range
  - 129.240.0.0/16       # UiO IPv4 range
  - 2001:700:200::/48    # UiB IPv6 range
  - 2001:700:100::/40    # UiO IPv6 range

# Whitelisted projects
project_name:
  - nrec-exampleproject     # example
  - PRIVATE-example.uio.no  # example

# Region specific whitelist
region:
  osl:
    rule_id:
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  # example
    secgroup_id:
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  # example
  bgo:
    rule_id:
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  # example
    secgroup_id:
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  # example
