---
direction:
  - egress
protocol:
  - ipv6-icmp
  - icmp
remote_group_id: ["!None"]
remote_ip_prefix:
  - 129.177.0.0/16
  - 129.240.0.0/16
  - 2001:700:200::/48
  - 2001:700:100::/40
port:
  - 22
  - 80
  - 443
