---
default:
  num_resources: 3
osl:
  num_resources: 4
bgo:
  num_resources: 8
test01:
  num_resources: 3
test02:
  num_resources: 3
local1:
  num_resources: 3
local2:
  num_resources: 1
vagrant:
  num_resources: 1
tos:
  num_resources: 1
