---
default:
  'cirros':
    'name':             'CirrOS debug image'
    'depricated':       'Outdated (CirrOS)'
    'url':              'http://download.cirros-cloud.net/0.3.5/'
    'latest':           'cirros-0.3.5-x86_64-disk.img'
    'checksum_file':    'MD5SUMS'
    'checksum':         'md5'
    'visibility':       'private'
    'disk_format':      'qcow2'
    'min_ram':          256
    'min_disk':         1
  'centos6':
    'name':             'GOLD CentOS 6'
    'depricated':       'Outdated (CentOS 6)'
    'url':              'http://cloud.centos.org/centos/6/images/'
    'latest':           'CentOS-6-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          1024
    'min_disk':         8
  'centos7':
    'name':             'GOLD CentOS 7'
    'depricated':       'Outdated (CentOS 7)'
    'url':              'http://cloud.centos.org/centos/7/images/'
    'latest':           'CentOS-7-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'centos8':
    'name':             'GOLD CentOS 8'
    'depricated':       'Outdated (CentOS 8)'
    'url':              'http://cloud.centos.org/centos/8/x86_64/images/'
    'latest':           'CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          1024
    'min_disk':         8
  'fedora_33':
    'name':             'GOLD Fedora 33'
    'depricated':       'Outdated (Fedora 33)'
    'url':              'https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/'
    'latest':           'Fedora-Cloud-Base-33-1.2.x86_64.qcow2'
    'checksum_file':    'Fedora-Cloud-33-1.2-x86_64-CHECKSUM'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'ubuntu1604':
    'name':             'GOLD Ubuntu server 16.04'
    'depricated':       'Outdated (Ubuntu 16.04)'
    'url':              'http://cloud-images.ubuntu.com/xenial/current/'
    'latest':           'xenial-server-cloudimg-amd64-disk1.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'ubuntu1804':
    'name':             'GOLD Ubuntu server 18.04'
    'depricated':       'Outdated (Ubuntu 18.04)'
    'url':              'http://cloud-images.ubuntu.com/bionic/current/'
    'latest':           'bionic-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'ubuntu1910':
    'name':             'GOLD Ubuntu server 19.10'
    'depricated':       'Outdated (Ubuntu 19.10)'
    'url':              'http://cloud-images.ubuntu.com/eoan/current/'
    'latest':           'eoan-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'debian9':
    'name':             'GOLD Debian 9'
    'depricated':       'Outdated (Debian 9)'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-9/'
    'latest':           'debian-9-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'debian10':
    'name':             'GOLD Debian 10'
    'depricated':       'Outdated (Debian 10)'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-10/'
    'latest':           'debian-10-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          768
    'min_disk':         8
  'winsrv2016std':
    'name':             'GOLD Windows Server 2016 Standard'
    'depricated':       'Outdated (Windows Server 2016 Standard)'
    'url':              'http://genisys.uib.no/images/'
    'latest':           'win2016-server.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'visibility':       'public'
    'disk_format':      'qcow2'
    'min_ram':          4090
    'min_disk':         39
