---
# Use empty value for None
desc: 'Manage host aggregates! Use <action> -h for help on each action'
actions:
  'list':           'List host aggregates'
  'show':           'Show host aggregates'
  'instances':      'List all instances in the aggregate'
  'stop-instance':  'Stop all instances in aggregate and save state'
  'start-instance': 'Start all instances which have running saved state'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
    'weight':   60
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  'aggregate':
    'sub':      ['show', 'instances', 'stop-instance', 'start-instance']
    'metavar':  'aggregate'
  '--no-purge':
    'sub':      ['stop-instance']
    'dest':     'purge'
    'default':  false
    'help':     'purge state db before adding new state'
    'action':   'store_const'
    'const':    true
