---
desc:           'Helper script to move from personal project to demo.'
actions:
  'projects':   'List all demo projects'
  'instances':  'List all instances in demo projects'
  'expired':    'Notify demo project users about expired instances'
  'delete':     'Delete obsolete demo instances'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  '--notify':
    'sub':      ['expired']
    'dest':     'notify'
    'help':     'Toggle notification (email to users)'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--force':
    'sub':      ['expired', 'delete']
    'dest':     'force'
    'help':     'Skip interactive confirmation'
    'action':   'store_const'
    'const':    true
    'default':  false
