---
desc:       'Helper script to move from personal project to demo.'
actions:
  'list':       'List all demo projects'
  'instances':  'List all instances in demo projects'
  'expired':    'Notify demo project users about expired instances'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  '-t':
    'sub':      ['expired']
    'dest':     'template'
    'help':     'mail template file. See notify/'
    'required': true
  '-d':
    'sub':      ['expired']
    'dest':     'day'
    'help':     'number of days instances have run'
    'required': true
