---
desc:                   'Manage flavor classes. Defaults to all regions'
actions:
  'list':               'List all flavors of a class'
  'update':             'Create or update all flavors of class'
  'purge':              'Purge flavor(s) not defined in config (cleanup)'
  'delete':             'Delete all flavors of a class'
  'grant':              'Grant access to a flavor for a project'
  'revoke':             'Revoke access to a flavor for a project'
  'list-access':        'List project with access to flavors of this class'
  'instances':          'List instances with flavor this class'
  'available-flavors':  'List all available flavor files'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  'flavor':
    'sub':       ['list', 'list-access' ,'update', 'grant', 'revoke', 'purge', 'delete','instances']
    'metavar':   'flavor'
    'help':      'flavor class name (e.g. m1)'
  'project':
    'sub':       ['grant', 'revoke']
    'metavar':   'project'
    'help':      'project name (e.g. iaas-team)'
    'weight':     10
