---
desc:             'Get metric from gnocchi'
actions:
  'list_metrics': 'List all metrics'
  'get_cpu_util': 'foo'
  
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--start':
    'dest':     start
    'help':     'start date (YYYY-MM-DD) Defaults to yesterday'
  '--end':
    'dest':     end
    'help':     'end date (YYYY-MM-DD) Defaults to today'
  '--host':
    'dest':     host
    'help':     'Hypervisor hostname, either hostname or FQDN'

