---
desc:             'Get metric from gnocchi'
actions:
  'list_samples': 'List all samples'

opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--start':
    'dest':     start
    'help':     'start date (YYYY-MM-DD) Defaults to yesterday'
  '--end':
    'dest':     end
    'help':     'end date (YYYY-MM-DD) Defaults to today'
