---
desc:           'Manage host aggregate groups of compute nodes'
actions:
  'list':       'List all aggregates'
  'show':       'Show aggregate information'
  'instances':  'List instances in aggregate'
  'users':      'List users with instances in aggregate'
  'notify':     'Notify all users with instances in aggregate of migration'
  'migrate':    'Migrate all instances out of aggregate'
  'activate':   'Enable aggregate and disable all other aggregates'
  'terminate':
opt_args:
  'aggregate':
    'sub':      ['show', 'instances', 'users', 'notify', 'migrate', 'activate','terminate']
    'metavar':  'aggregate'
  '-m':
    'sub':      'notify'
    'dest':     'date'
    'help':     'date message'
    'metavar':  'date'
  '--az':
    'sub':      'list'
    'dest':     'az'
    'help':     'availability zone'
  '--limit':
    'sub':      ['migrate', 'terminate']
    'type':     int
    'dest':     'limit'
    'help':     'number of instances to migrate before sleep'
    'default':  25
  '--sleep':
    'sub':      'migrate'
    'dest':     'sleep'
    'type':     int
    'help':     'number of seconds to sleep'
    'default':  180
  '--hard-limit':
    'sub':      'migrate'
    'dest':     'hard_limit'
    'action':   'store_const'
    'const':    true
    'help':     'exit script after migration of --limit instances'
    'default':  false
  '--host':
    'sub':      ['migrate','instances']
    'dest':     'host'
    'help':     'only use this host in the aggregate'
  '--detailed':
    'sub':      ['list']
    'dest':     'detailed'
    'help':     'also show aggregate metadata'
    'action':   'store_const'
    'const':    true
    'default':  False
  '--template':
    'sub':      ['notify', 'terminate']
    'dest':     'template'
    'help':     'mail template file. See notify/'
    'default':  'notify/notify_reboot.txt'
