---
desc:   'Migate instances. Only use on hosts with shared storage! For local storage see aggregate.py'
actions:
  list:     'List instances for migration'
  migrate:  'Migrate instances from host'
  evacuate: 'Evacuate all instances from host'
opt_args:
  'source':
    'metavar':  'source'
    'help':     'Source host. Use either hostname or FQDN'
  'target':
    'sub':      ['migrate']
    'metavar':  'target'
    'help':     'Target host. Use either hostname or FQDN'
  '--limit':
    'sub':      ['migrate', 'evacuate']
    'type':     int
    'dest':     'limit'
    'metavar':  '<int>'
    'help':     'number of instances to consider for migration before exit'
  '--sleep':
    'sub':      ['migrate', 'evacuate']
    'dest':     'sleep'
    'metavar':  '<int>'
    'type':     int
    'help':     'number of seconds to sleep between instances'
    'default':  15
  '--no-disable':
    'sub':      ['migrate']
    'dest':     'no_disable'
    'help':     'do not disable source hypervisor'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--large':
    'sub':      ['migrate']
    'dest':     'large'
    'help':     'only migrate large instances'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--large-ram':
    'sub':      ['migrate']
    'dest':     'large_ram'
    'metavar':  '<int>'
    'type':     int
    'help':     'large instance defined by this amount of ram (MB)'
    'default':  16385
  '--aggregate':
    'sub':      'evacuate'
    'dest':     'aggregate'
    'help':     'host aggregate to evacuate'
    'default':  'central1'
