---
desc:           'Manage swift object storage'
actions:
  'grant':      'Grant all users of a project access to use object storage'
  'revoke':     'Revoke all users of a project access to use object storage'
  'show':       'Show object storage usage for a project'
  'list':       'List all containers owned by a project'
  'purge':      'Delete all containers and objects owned by a project'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  '-u':
    'sub':      ['grant','revoke']
    'dest':     'users'
    'help':     'email of a valid openstack user (can be used multiple times)'
    'action':   'append'
  '--force':
    'sub':      ['purge']
    'dest':     'force'
    'help':     'skip interactive confirmation'
    'action':   'store_const'
    'const':    true
    'default':  false
  'project':
   'sub':       ['grant', 'revoke', 'show', 'list', 'purge']
   'metavar':   'project'
