---
desc:   'Project management for UH-IaaS'
actions:
  'list':         'List project. Use -f to filter result by project type'
  'show':         'Show all attributes for a project'
  'show-access':  'Show roles in project'
  'show-quota':   'Show quota for project'
  'create':       'Create a new project and grant admin access if valid user'
  'grant':        'Grant access to project for user.'
  'delete':       'Delete project and all resources'
  'instances':    'List of all instances in project'
  'extend':       'Change or set the endate for a project'
#  'update': 'TODO'
#  'revoke': 'TODO'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  'project':
   'sub':       ['show', 'show-access', 'show-quota', 'create', 'grant', 'delete', 'instances', 'extend']
   'metavar':   'project'
  'user':
   'sub':       ['create-private']
   'metavar':   'user'
  '--region':
    'sub':      ['show', 'create', 'instances', 'show-access', 'show-quota']
    'dest':     'region'
    'help':     'specify region'
  '--end':
    'sub':      ['create', 'extend', 'create-private']
    'dest':     'enddate'
    'help':     'set end date for projects (DD.MM.YYYY)'
  '-f':
    'sub':      ['list']
    'dest':     'filter'
    'help':     'filter by project type'
    'default':  'all'
    'choices':  ['all', 'admin', 'demo', 'personal', 'research', 'education', 'vgpu', 'test', 'hpc']
  '-a':
    'sub':      ['create']
    'dest':     'admin'
    'help':     'email for admin user (can be non openstack user)'
    'required': true
  '-t':
    'sub':      ['create']
    'dest':     'type'
    'help':     'project type'
    'choices':  ['admin', 'demo', 'personal', 'research', 'education', 'course', 'test', 'hpc']
    'required': true
  '--desc':
    'sub':      ['create']
    'dest':     'desc'
    'metavar':  'description'
    'help':     'project project description'
  '-o':
    'sub':      ['create']
    'dest':     'org'
    'help':     'Associated organization'
    'choices':  ['nrec', 'uio', 'uib', 'uit', 'ntnu', 'nmbu', 'vetinst']
    'required': true
  '--contact':
    'sub':      ['create']
    'dest':     'contact'
    'help':     'Contact email (mailing list)'
  '-q':
    'sub':      ['create', 'create-private']
    'dest':     'quota'
    'help':     'quota class'
    'choices':  ['small', 'medium', 'large']
  '-u':
    'sub':      ['grant']
    'dest':     'users'
    'help':     'email of a valid openstack user (can be used multiple times)'
    'action':   'append'
    'required': true
  '--force':
    'sub':      ['create', 'delete', 'create-private']
    'dest':     'force'
    'help':     'skip interactive confirmation'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--rt':
    'sub':      ['create', 'grant', 'create-private']
    'dest':     'rt'
    'help':     'request tracker ticket number or link'
    'metavar':  'request tracker'
  '-m':
    'sub':      ['create', 'grant', 'create-private']
    'dest':     'mail'
    'help':     'Send an autogenerated mail to RT after creating a project. Send to RT and the user when granting access.'
    'action':   'store_const'
    'const':    true
    'default':  False
  '-n':
    'sub':      [ 'show-quota' ]
    'dest':     'service'
    'metavar':  'service type'
    'help':     'openstack service type'
    'choices':  ['all', 'nova', 'cinder', 'neutron']
    'default':  'all'
