---
desc:   'Reports for NREC'
actions:
  'list':         'List projects. Use -f to filter result by project type'
  'show':         'Show a single project'
  'user':         'Show projects for user'
  'vendorapi':    'Create data for Nova vendor API'
  'mail':         'Send email to users'
  'enddate':      'Send alerts to admin/contact about pending enddate'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'Openstack domain to use'
    'default':  'Dataporten'
  '-f':
    'sub':      ['list']
    'dest':     'filter'
    'help':     'Filter by project type'
    'default':  'test'
    'choices':  ['all', 'admin', 'demo', 'personal', 'research', 'education', 'vgpu', 'test', 'hpc']
  '--detail':
    'sub':      ['list','show','user','mail','enddate']
    'dest':     'detail'
    'help':     'Show details about project resource consumption'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--admin':
    'sub':      ['user','mail']
    'dest':     'admin'
    'help':     'Display only projects where user is admin'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--outdir':
    'sub':      ['vendorapi']
    'dest':     'outdir'
    'help':     'Directory in which to create JSON output files'
  '--template':
    'sub':      ['mail','enddate']
    'dest':     'template'
    'required': true
    'help':     'Path to email template'
  '--subject':
    'sub':      ['mail']
    'dest':     'subject'
    'required': true
    'help':     'Mail subject'
  '--from':
    'sub':      ['mail','enddate']
    'dest':     'fromaddr'
    'help':     'Address for From and Reply-To (default: support@nrec.no)'
  '--user':
    'sub':      ['mail']
    'dest':     'mail_user'
    'help':     'Send to only this user'
  '--force':
    'sub':      ['mail','enddate']
    'dest':     'force'
    'help':     'Skip interactive confirmation'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--days':
    'sub':      ['enddate']
    'dest':     'days'
    'type':     int
    'required': true
    'help':     'Number of days until enddate as criterion for alert'
  '--list':
    'sub':      ['enddate']
    'dest':     'list'
    'help':     'Simply list projects'
  'project':
   'sub':       ['show']
   'metavar':   'project'
  'user':
   'sub':       ['user']
   'metavar':   'user'

