---
desc:   'Management of security groups'
actions:
  'list':     'List all none whitelisted security group rules'

opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
    'weight':   100
  '--region':
    'dest':     'region'
    'help':     'only use this region'
  '-v':
    'sub':      ['list']
    'dest':     'verbose'
    'help':     'Verbosity level (0-3)'
    'type':     'int'
    'metavar':  '<integer>'
    'default':  0
  '-y':
    'sub':      ['list']
    'dest':     'assume_yes'
    'help':     'Automatic yes to prompts; assume "yes" as answer to all prompts'
    'action':   'store_const'
    'const':    true
    'default':  false
