---
# Use empty value for None
desc: 'Manage our users. Use <action> -h for help on each action'
actions:
  'list':           'List of users and show stats based on email domain'
  'show':           'Show user information'
  'delete':         'Delete user'
  'rename':         'Use this when user changes affiliation'
  'password':       'Reset API password for user'
  'create':         'Create a user new local API only user'
  'enable':         'Enable a user'
  'disable':        'Disable a user'
  'validate':       'Validate user against FEIDE ldap'
  'deactivate':     'Deactivate all users not found in LDAP.'
  'list-disabled':  'List disabled users'
  'purge':          'Purge disabled users'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
  'user':
    'sub':      ['show', 'password', 'delete', 'create', 'enable', 'disable']
    'help':     'username should be email addresses'
    'metavar':  'username'
  '--new':
    'sub':      'rename'
    'dest':     'new'
    'help':     'new user email (case sensitive)'
    'metavar':  'user'
    'required': true
  '--old':
    'sub':      'rename'
    'dest':     'old'
    'help':     'old user email (case sensitive)'
    'metavar':  'user'
    'required': true
  '-o':
    'sub':      'show'
    'dest':     'obj_type'
    'metavar':
    'help':     'user object type to show'
    'choices':   ['api', 'dataporten', 'group', 'projects']
    'default':  'projects'
  '-a':
    'sub':      'create'
    'dest':     'admin'
    'help':     'email to the FEIDE user responsible for the new local user'
    'metavar':  'admin'
    'required': true
  '--email':
    'sub':      'create'
    'dest':     'email'
    'help':     'email used for contact (otherwise same as username)'
    'metavar':  'email'
  '--desc':
    'sub':      'create'
    'dest':     'description'
    'help':     'user description'
  '--end':
    'sub':      'create'
    'dest':     'enddate'
    'help':     'set end date for projects (DD.MM.YY)'
  '--password':
    'sub':      'create'
    'dest':     'password'
    'help':     'user password (default: random password)'
  '--limit':
    'sub':      ['validate', 'deactivate', 'purge']
    'dest':     'limit'
    'help':     'Limit the number of users'
  '--force':
    'sub':      ['delete', 'disable', 'purge']
    'dest':     'force'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--org':
    'sub':      ['validate', 'deactivate', 'list-disabled', 'purge']
    'dest':     'org'
    'help':     'only do one user organization, e.g. uio'
    'default':  'all'
  '--reason':
    'sub':      ['disable', 'purge']
    'dest':     'reason'
    'help':     'Reason for disabling user'
    'choices':   ['deleted', 'teppe']
    'required': true
  '--date':
    'sub':      ['disable']
    'dest':     'date'
    'help':     'Set the date for when user was disabled (YYYY-MM-DD). Default = today'
  '--days':
    'sub':      ['purge']
    'dest':     'days'
    'help':     'Number of days since the user was disabled. Default = 90'
    'default':  90
    'type':     int
    
